# Generated by Django 4.2 on 2023-05-03 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_articlecollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCollection',
            new_name='ArticlesCollection',
        ),
    ]
