# Generated by Django 4.2 on 2023-05-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_favorites_favoritearticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicarticlescollection',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='publicarticlescollection',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalArticlesCollection',
        ),
        migrations.DeleteModel(
            name='PublicArticlesCollection',
        ),
    ]
