# Generated by Django 4.2 on 2023-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_article_author',
            field=models.BooleanField(default=False),
        ),
    ]
