# Generated by Django 4.2 on 2023-05-08 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_userreadings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReadings',
            new_name='UserReading',
        ),
    ]
